services:
  rate-service:
    build:
      context: ./rate-service
      dockerfile: Dockerfile
    container_name: rate-service
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    restart: unless-stopped

  allocation-service:
    build:
      context: ./allocation-service
      dockerfile: Dockerfile
    container_name: allocation-service
    ports:
      - "3001:3000"
    networks:
      - microservices-network
    restart: unless-stopped


  logistic-service:
    build:
      context: ./logistic-service
      dockerfile: Dockerfile
    container_name: logistic-service
    ports:
      - "3002:3000"
    networks:
      - microservices-network
    restart: unless-stopped


  aggregation-service:
    build:
      context: ./aggregation-service
      dockerfile: Dockerfile
    container_name: aggregation-service
    ports:
      - "3003:3000"
    networks:
      - microservices-network
    depends_on:
      - rate-service
      - allocation-service
      - logistic-service
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge
    name: microservices-network